package com.dg.mdsrose.view;

import com.dg.mdsrose.user.model.User;
import com.dg.mdsrose.user.UserService;
import com.dg.mdsrose.user.UserSession;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Optional;

public class Login extends BaseJFrame implements ActionListener {
    private JButton loginButton;
    private JPanel loginPanel;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JButton goToSignupButton;

    private final UserService userService = UserService.getInstance();
    private final UserSession userSession = UserSession.getInstance();

    public Login() {
        createAndShowGUI();
        loginButton.addActionListener(this);
        goToSignupButton.addActionListener(this);
    }

    @Override
    protected JPanel setContentPanel() {
        return loginPanel;
    }

    @Override
    protected String setTitle() {
        return "Login";
    }

    @Override
    protected int setDefaultCloseOperation() {
        return WindowConstants.EXIT_ON_CLOSE;
    }

    @Override
    protected Dimension setPreferredSize() {
        return null;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(loginButton)) {
            login();
        } else if (e.getSource().equals(goToSignupButton)) {
            goToSignup();
        }
    }

    private void login() {
        Optional<User> login = userService.login(usernameField.getText(), new String(passwordField.getPassword()));
        if (login.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Invalid username or password",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        User user = login.get();
        userSession.init(user);

        new Homepage();
        this.dispose();
    }

    private void goToSignup() {
        new Signup();
        this.dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginPanel = new JPanel();
        loginPanel.setLayout(new GridLayoutManager(3, 3, new Insets(10, 10, 10, 10), -1, -1));
        loginPanel.setMinimumSize(new Dimension(385, 136));
        loginPanel.setPreferredSize(new Dimension(385, 136));
        usernameLabel = new JLabel();
        usernameLabel.setText("Username");
        loginPanel.add(usernameLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usernameField = new JTextField();
        loginPanel.add(usernameField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setText("Password");
        loginPanel.add(passwordLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField = new JPasswordField();
        loginPanel.add(passwordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Login");
        loginPanel.add(loginButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        goToSignupButton = new JButton();
        goToSignupButton.setText("Signup");
        loginPanel.add(goToSignupButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginPanel;
    }

}