package com.dg.mdsrose.view;

import com.dg.mdsrose.project.InMemoryProjectService;
import com.dg.mdsrose.project.dataset.CsvStrategy;
import com.dg.mdsrose.project.dataset.DataStrategy;
import com.dg.mdsrose.project.dataset.DatasetStrategy;
import com.dg.mdsrose.util.DatasetFileFilter;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.Objects;

import static com.dg.mdsrose.enums.FileMetadata.CSV;
import static com.dg.mdsrose.enums.FileMetadata.DATA;

public class ProjectCreation extends BaseJFrame implements ActionListener {
    private JTextField pathDatasetField;
    private JButton selectDatasetButton;
    private JLabel selectDatasetLabel;
    private JPanel newProjectPanel;
    private JButton confirmButton;


    public ProjectCreation() {
        createAndShowGUI();
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                new Homepage();
            }
        });
        selectDatasetButton.addActionListener(this);
        confirmButton.addActionListener(this);
        InMemoryProjectService.getInstance()
            .clearTables();
    }

    @Override
    protected String setTitle() {
        return "New Project";
    }

    @Override
    protected JPanel setContentPanel() {
        return newProjectPanel;
    }

    @Override
    protected Dimension setPreferredSize() {
        return null;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(this.selectDatasetButton)) {
            selectFile();
        } else if (e.getSource().equals(this.confirmButton)) {
            confirmFile();
        }
    }

    private void confirmFile() {
        DatasetStrategy datasetStrategy;
        if (pathDatasetField.getText().endsWith(DATA.getExtension())) {
            datasetStrategy = new DataStrategy();
        } else if (pathDatasetField.getText().endsWith(CSV.getExtension())) {
            datasetStrategy = new CsvStrategy();
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Select a valid dataset.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        datasetStrategy.showFrame(this.pathDatasetField.getText());
        this.dispose();
    }

    private void selectFile() {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser.setFileFilter(new DatasetFileFilter());
        jFileChooser.setAcceptAllFileFilterUsed(false);

        File file;
        int returnDialog = jFileChooser.showOpenDialog(null);
        if (returnDialog == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser.getSelectedFile();
        } else {
            System.out.println("No File Selected");
            return;
        }
        if (Objects.isNull(file)) {
            System.out.println("No Valid File Selected");
        }
        this.pathDatasetField.setText(file.getAbsolutePath());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        newProjectPanel = new JPanel();
        newProjectPanel.setLayout(new GridLayoutManager(5, 2, new Insets(10, 10, 10, 10), -1, -1));
        pathDatasetField = new JTextField();
        pathDatasetField.setEditable(false);
        newProjectPanel.add(pathDatasetField, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        selectDatasetLabel = new JLabel();
        selectDatasetLabel.setText("Select Dataset...");
        newProjectPanel.add(selectDatasetLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        newProjectPanel.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        newProjectPanel.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        selectDatasetButton = new JButton();
        selectDatasetButton.setText("Select");
        newProjectPanel.add(selectDatasetButton, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        confirmButton = new JButton();
        confirmButton.setText("Confirm");
        newProjectPanel.add(confirmButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return newProjectPanel;
    }

}
